definitions:
  handler.ResponseHTTP:
    properties:
      data:
        type: object
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: { }
paths:
  /v1/books:
    get:
      consumes:
        - application/json
      description: Get all books
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handler.ResponseHTTP'
      summary: Get all books
      tags:
        - books
swagger: "2.0"
